baseURL = "https://bookshop.build/"
languageCode = "en-us"
title = "Hugo Bookshop Cucumber"
copyright = "ðŸŽ‰"

[module]
replacements = "bookshop.test/components -> ../../component-lib,github.com/cloudcannon/bookshop/hugo/v3 -> ../../../../../../hugo/v3/"

[[module.imports]]
path = 'bookshop.test/components'
