name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.6', '2.7']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install node dependencies
      run: yarn install --immutable
      working-directory: ./javascript-modules
    - name: Vendor node modules into ruby packages
      run: ./scripts/publish.js vendor
    - name: Set up jekyll-bookshop Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: ./generator-plugins/jekyll/jekyll-bookshop
    - name: Set up cloudcannon-jekyll-bookshop Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: ./generator-plugins/jekyll/cloudcannon-jekyll-bookshop
    - name: Run jekyll-bookshop tests
      run: bundle exec rake test
      working-directory: ./generator-plugins/jekyll/jekyll-bookshop
    - name: Run cloudcannon-jekyll-bookshop tests
      run: bundle exec rake test
      working-directory: ./generator-plugins/jekyll/cloudcannon-jekyll-bookshop
